version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    env_file: .env
    environment:
      - POSTGRES_DB=tradingbotdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}