# Generated by Django 5.0.4 on 2024-04-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbot', '0002_rename_user_trader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
